import '@element-plus/components/src/base/style/css'
import '@element-plus/components/src/input/style/css'
import '@element-plus/components/src/button/style/css'
import '@element-plus/components/src/checkbox/style/css'
import '@element-plus/components/src/checkbox-group/style/css'
import '@element-plus/theme-chalk/dist/transfer.css'
