import '@element-plus/components/src/base/style/css'
import '@element-plus/components/src/input/style/css'
import '@element-plus/components/src/tag/style/css'
import '@element-plus/components/src/scrollbar/style/css'
import '@element-plus/components/src/popper/style/css'
import '@element-plus/components/src/virtual-list/style/css'
import '@element-plus/theme-chalk/dist/select-v2.css'
