import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/dist/table.css'
import '@element-plus/components/checkbox/style/css'
import '@element-plus/components/tag/style/css'
import '@element-plus/components/tooltip/style/css'
import '@element-plus/components/scrollbar/style/css'
