packages:
  - packages/*
  - docs
  - play
  - internal/*

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  puppeteer: true
  vue-demi: true

catalog:
  '@ctrl/tinycolor': ^4.2.0
  '@element-plus/icons-vue': ^2.3.2
  '@floating-ui/dom': ^1.7.6
  '@popperjs/core': npm:@sxzz/popperjs-es@^2.11.8
  '@vitejs/plugin-vue': ^5.2.4
  '@vitejs/plugin-vue-jsx': ^4.2.0
  '@vue/server-renderer': ^3.5.30
  '@vue/shared': ^3.5.30
  '@vue/test-utils': ^2.4.6
  '@vueuse/core': 12.8.2
  lodash-unified: ^1.0.3
  normalize-wheel-es: ^1.2.0
  vue: ^3.5.30
  vue-component-type-helpers: ^3.2.6
  # vitest: ^2.0.5

overrides:
  jwa: ^1.4.2 # 20697
  typescript: $typescript

patchedDependencies:
  async-validator@4.2.5: patches/async-validator@4.2.5.patch #16757

peerDependencyRules:
  ignoreMissing:
    - vite
    - react
    - react-dom

shellEmulator: true
strictPeerDependencies: false
