packages:
  - packages/*
  - docs
  - play
  - internal/*

catalog:
  '@ctrl/tinycolor': ^3.4.1
  '@element-plus/icons-vue': ^2.3.2
  '@vue/shared': ~3.2.37
  '@vueuse/core': ^10.11.0
  '@vue/test-utils': ^2.0.0
  'lodash-unified': ^1.0.3
  'type-fest': ^2.14.0
  '@popperjs/core': npm:@sxzz/popperjs-es@^2.11.7
  'normalize-wheel-es': ^1.2.0
  csstype: ^2.6.20
  '@floating-ui/dom': ^1.0.1
  vue: ~3.2.37

onlyBuiltDependencies:
  - 'es5-ext'
  - 'esbuild'
  - 'fsevents'
  - 'puppeteer'
  - 'vue-demi'

overrides:
  'typescript': '$typescript'
  'jwa': '^1.4.2' # 20697

patchedDependencies:
  async-validator@4.2.5: patches/async-validator@4.2.5.patch #16757

peerDependencyRules:
  ignoreMissing:
    - 'vite'
    - 'react'
    - 'react-dom'

shamefullyHoist: true

shellEmulator: true

strictPeerDependencies: false
