import '@element-plus/components/base/style'
import '@element-plus/components/input/style/index'
import '@element-plus/components/tag/style/index'
import '@element-plus/components/option/style/index'
import '@element-plus/components/option-group/style/index'
import '@element-plus/components/scrollbar/style/index'
import '@element-plus/components/popper/style/index'
import '@element-plus/theme-chalk/src/select.scss'
