import '@element-plus/components/base/style'
import '@element-plus/theme-chalk/src/drawer.scss'
import '@element-plus/components/overlay/style'
import '@element-plus/components/splitter/style'
import '@element-plus/components/splitter-panel/style'
