import '@element-plus/components/src/base/style/css'
import '@element-plus/theme-chalk/dist/container.css'
import '@element-plus/theme-chalk/dist/aside.css'
import '@element-plus/theme-chalk/dist/footer.css'
import '@element-plus/theme-chalk/dist/header.css'
import '@element-plus/theme-chalk/dist/main.css'
