<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect width="280" height="180" fill="var(--el-fill-color-light)" />
    <g filter="url(#filter0_d_13239_208943)">
      <rect
        x="65"
        y="46"
        width="150"
        height="89"
        rx="2"
        fill="var(--el-bg-color-overlay)"
      />
      <rect
        x="64.7"
        y="45.7"
        width="150.6"
        height="89.6"
        rx="2.3"
        stroke="var(--el-border-color-dark)"
        stroke-width="0.6"
      />
    </g>
    <path
      d="M65 48C65 46.8954 65.8954 46 67 46H213C214.105 46 215 46.8954 215 48V62H65V48Z"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="77"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="97"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="117"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="137"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="157"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="177"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="197"
      y="53"
      width="6"
      height="2"
      rx="1"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="175"
      y="69"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="195"
      y="69"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="175"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="95"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="135"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="155"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="195"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="115"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="75"
      y="85"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="175"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="95"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="135"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="195"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="115"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="115"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-color-primary)"
    />
    <rect
      x="112.5"
      y="98.5"
      width="13"
      height="13"
      rx="1.5"
      stroke="var(--el-color-primary)"
    />
    <rect
      x="155"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="75"
      y="101"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="175"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="95"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="135"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="195"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="115"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="155"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <rect
      x="75"
      y="117"
      width="8"
      height="8"
      rx="2"
      fill="var(--el-border-color-light)"
    />
    <defs>
      <filter
        id="filter0_d_13239_208943"
        x="51.0666"
        y="32.0671"
        width="177.867"
        height="116.866"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood flood-opacity="0" result="BackgroundImageFix" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset />
        <feGaussianBlur stdDeviation="6.66667" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_13239_208943"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_13239_208943"
          result="shape"
        />
      </filter>
    </defs>
  </svg>
</template>
