<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect width="280" height="180" fill="var(--el-fill-color-light)" />
    <rect
      x="104"
      y="78"
      width="24"
      height="24"
      fill="var(--el-color-primary-light-8)"
    />
    <rect
      x="128"
      y="78"
      width="24"
      height="24"
      fill="var(--el-color-primary-light-5)"
    />
    <rect
      x="152"
      y="78"
      width="24"
      height="24"
      fill="var(--el-color-primary)"
    />
  </svg>
</template>
