<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g clip-path="url(#clip0_12777_163869)">
      <rect width="280" height="180" fill="var(--el-fill-color-light)" />
      <g filter="url(#filter1_d_12777_163869)">
        <rect
          x="60"
          y="41"
          width="150"
          height="98"
          rx="2"
          fill="var(--el-bg-color-overlay)"
        />
        <rect
          x="59.7"
          y="40.7"
          width="150.6"
          height="98.6"
          rx="2.3"
          stroke="var(--el-border-color-dark)"
          stroke-width="0.6"
        />
      </g>
      <path
        d="M60 43C60 41.8954 60.8954 41 62 41H208C209.105 41 210 41.8954 210 43V57H60V43Z"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="170"
        y="61"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="190"
        y="61"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="170"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="90"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="130"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="150"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="190"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="110"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="70"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="150"
        y="77"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-color-primary)"
      />
      <rect
        x="147.5"
        y="74.5"
        width="13"
        height="13"
        rx="1.5"
        stroke="var(--el-color-primary)"
      />
      <rect
        x="170"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="90"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="130"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="190"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="110"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="150"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="70"
        y="93"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="170"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="90"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="130"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="190"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="110"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="150"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="70"
        y="109"
        width="8"
        height="8"
        rx="2"
        fill="var(--el-border-color-light)"
      />
      <rect
        x="72"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
      <rect
        x="92"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
      <rect
        x="112"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
      <rect
        x="132"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
      <rect
        x="152"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
      <rect
        x="172"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
      <rect
        x="192"
        y="48"
        width="6"
        height="2"
        rx="1"
        fill="var(--el-border-color-dark)"
      />
    </g>
    <defs>
      <filter
        id="filter0_d_12777_163869"
        x="46.0667"
        y="48.0671"
        width="177.867"
        height="47.8659"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood flood-opacity="0" result="BackgroundImageFix" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset />
        <feGaussianBlur stdDeviation="6.66667" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_12777_163869"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_12777_163869"
          result="shape"
        />
      </filter>
      <filter
        id="filter1_d_12777_163869"
        x="46.0667"
        y="27.0671"
        width="177.867"
        height="125.866"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood flood-opacity="0" result="BackgroundImageFix" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset />
        <feGaussianBlur stdDeviation="6.66667" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.05 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_12777_163869"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_12777_163869"
          result="shape"
        />
      </filter>
    </defs>
  </svg>
</template>
