<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <g clip-path="url(#clip0_input_otp)">
      <rect width="280" height="180" fill="var(--el-fill-color-light)" />
      <g filter="url(#filter0_d_input_otp)">
        <rect
          x="80"
          y="78"
          width="24"
          height="24"
          rx="2"
          fill="var(--el-fill-color-blank)"
        />
        <rect
          x="79.7"
          y="77.7"
          width="24.6"
          height="24.6"
          rx="2.3"
          stroke="var(--el-border-color-dark)"
          stroke-width="0.6"
        />
        <rect
          x="112"
          y="78"
          width="24"
          height="24"
          rx="2"
          fill="var(--el-fill-color-blank)"
        />
        <rect
          x="111.7"
          y="77.7"
          width="24.6"
          height="24.6"
          rx="2.3"
          stroke="var(--el-color-primary)"
          stroke-width="0.6"
        />
        <rect
          x="144"
          y="78"
          width="24"
          height="24"
          rx="2"
          fill="var(--el-fill-color-blank)"
        />
        <rect
          x="143.7"
          y="77.7"
          width="24.6"
          height="24.6"
          rx="2.3"
          stroke="var(--el-border-color-dark)"
          stroke-width="0.6"
        />
        <rect
          x="176"
          y="78"
          width="24"
          height="24"
          rx="2"
          fill="var(--el-fill-color-blank)"
        />
        <rect
          x="175.7"
          y="77.7"
          width="24.6"
          height="24.6"
          rx="2.3"
          stroke="var(--el-border-color-dark)"
          stroke-width="0.6"
        />
      </g>
      <rect
        x="123"
        y="86"
        width="2"
        height="8"
        rx="1"
        fill="var(--el-color-primary)"
      />
    </g>
    <defs>
      <clipPath id="clip0_input_otp">
        <rect width="280" height="180" fill="white" />
      </clipPath>
      <filter
        id="filter0_d_input_otp"
        x="66"
        y="64"
        width="148"
        height="52"
        filterUnits="userSpaceOnUse"
        color-interpolation-filters="sRGB"
      >
        <feFlood flood-opacity="0" result="BackgroundImageFix" />
        <feColorMatrix
          in="SourceAlpha"
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"
          result="hardAlpha"
        />
        <feOffset dy="4" />
        <feGaussianBlur stdDeviation="6" />
        <feComposite in2="hardAlpha" operator="out" />
        <feColorMatrix
          type="matrix"
          values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.04 0"
        />
        <feBlend
          mode="normal"
          in2="BackgroundImageFix"
          result="effect1_dropShadow_input_otp"
        />
        <feBlend
          mode="normal"
          in="SourceGraphic"
          in2="effect1_dropShadow_input_otp"
          result="shape"
        />
      </filter>
    </defs>
  </svg>
</template>
