<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect width="280" height="180" fill="var(--el-fill-color-light)" />
    <rect
      x="80"
      y="76"
      width="24"
      height="28"
      rx="2"
      fill="var(--el-fill-color-blank)"
    />
    <rect
      x="80"
      y="76"
      width="24"
      height="28"
      rx="2"
      stroke="var(--el-border-color-dark)"
    />
    <rect
      x="112"
      y="76"
      width="24"
      height="28"
      rx="2"
      fill="var(--el-fill-color-blank)"
    />
    <rect
      x="112"
      y="76"
      width="24"
      height="28"
      rx="2"
      stroke="var(--el-color-primary)"
    />
    <rect
      x="144"
      y="76"
      width="24"
      height="28"
      rx="2"
      fill="var(--el-fill-color-blank)"
    />
    <rect
      x="144"
      y="76"
      width="24"
      height="28"
      rx="2"
      stroke="var(--el-border-color-dark)"
    />
    <rect
      x="176"
      y="76"
      width="24"
      height="28"
      rx="2"
      fill="var(--el-fill-color-blank)"
    />
    <rect
      x="176"
      y="76"
      width="24"
      height="28"
      rx="2"
      stroke="var(--el-border-color-dark)"
    />

    <rect
      x="123"
      y="85"
      width="2"
      height="10"
      rx="1"
      fill="var(--el-color-primary)"
    />
  </svg>
</template>
