<template>
  <svg
    width="280"
    height="180"
    viewBox="0 0 280 180"
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    <rect width="280" height="180" fill="var(--el-fill-color-light)" />
    <circle cx="114" cy="54" r="3" fill="var(--el-color-primary)" />
    <circle cx="114" cy="90" r="3" fill="var(--el-border-color-dark)" />
    <circle cx="114" cy="126" r="3" fill="var(--el-border-color-dark)" />
    <line
      x1="114.15"
      y1="60"
      x2="114.15"
      y2="84"
      stroke="var(--el-border-color-dark)"
      stroke-width="0.3"
    />
    <line
      x1="114.15"
      y1="96"
      x2="114.15"
      y2="120"
      stroke="var(--el-border-color-dark)"
      stroke-width="0.3"
    />
    <rect
      x="127"
      y="51"
      width="45"
      height="4"
      rx="2"
      fill="var(--el-color-primary)"
    />
    <rect
      x="127"
      y="87"
      width="45"
      height="4"
      rx="2"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="127"
      y="123"
      width="45"
      height="4"
      rx="2"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="127"
      y="59"
      width="24"
      height="4"
      rx="2"
      fill="var(--el-color-primary)"
    />
    <rect
      x="127"
      y="95"
      width="24"
      height="4"
      rx="2"
      fill="var(--el-border-color-dark)"
    />
    <rect
      x="127"
      y="131"
      width="24"
      height="4"
      rx="2"
      fill="var(--el-border-color-dark)"
    />
  </svg>
</template>
