import '@element-plus/components/base/style'
import '@element-plus/theme-chalk/src/date-picker-panel.scss'
import '@element-plus/components/input/style'
import '@element-plus/components/scrollbar/style'
import '@element-plus/components/button/style'
