export { default as ElInfiniteScroll } from '@element-plus/components/infinite-scroll'
export { default as ElLoading } from '@element-plus/components/loading'
export { default as ElMessage } from '@element-plus/components/message'
export { default as ElMessageBox } from '@element-plus/components/message-box'
export { default as ElNotification } from '@element-plus/components/notification'
export { default as ElPopover } from '@element-plus/components/popover'
