export const klsPrefix = 'el-virtual-table'
export const ON_COLUMN_SORT = 'column-sort'
export const ON_ROW_EXPANDED = 'row-expanded'
export const ON_EXPANDED_ROWS_CHANGED = 'expanded-rows-changed'
export const ON_ROW_CLICKED = 'row-clicked'
export const ON_ROW_DB_CLICKED = 'row-db-clicked'
export const ON_SCROLL = 'scroll'
export const ON_ROWS_RENDERED = 'rows-rendered'
