import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/el-table.css'
import '@element-plus/components/checkbox/style/css'
import '@element-plus/components/tag/style/css'
import '@element-plus/components/tooltip/style/css'
