import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/g-table.css'
import '@element-plus/components/checkbox/style/css'
import '@element-plus/components/tooltip/style/css'
import '@element-plus/components/scrollbar/style/css'
