import '@element-plus/components/base/style'
import '@element-plus/theme-chalk/src/table.scss'
import '@element-plus/components/checkbox/style/index'
import '@element-plus/components/tag/style/index'
import '@element-plus/components/tooltip/style/index'
