import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/el-select-icon.css'
import '@element-plus/components/button/style/css'
import '@element-plus/components/pagination/style/css'
import '@element-plus/components/scrollbar/style/css'
import '@element-plus/components/tooltip/style/css'
