import '@element-plus/components/base/style'
import '@element-plus/theme-chalk/src/select-icon.scss'
import '@element-plus/components/button/style'
import '@element-plus/components/pagination/style'
import '@element-plus/components/scrollbar/style'
import '@element-plus/components/tooltip/style'
