import '@element-plus/components/src/base/style/css'
import '@element-plus/theme-chalk/dist/time-select.css'
import '@element-plus/components/src/scrollbar/style/css'
import '@element-plus/components/src/popper/style/css'
import '@element-plus/components/src/input/style/css'
import '@element-plus/components/src/select/style/css'
import '@element-plus/components/src/option/style/css'
