import '@element-plus/components/base/style/css'
import '@element-plus/theme-chalk/g-container.css'
import '@element-plus/theme-chalk/g-aside.css'
import '@element-plus/theme-chalk/g-footer.css'
import '@element-plus/theme-chalk/g-header.css'
import '@element-plus/theme-chalk/g-main.css'
