import '@element-plus/components/src/base/style'
import '@element-plus/components/src/input/style'
import '@element-plus/components/src/tag/style'
import '@element-plus/components/src/option/style'
import '@element-plus/components/src/option-group/style'
import '@element-plus/components/src/scrollbar/style'
import '@element-plus/components/src/popper/style'
import '@element-plus/theme-chalk/src/select.scss'
