import '@element-plus/components/src/base/style/css'
import '@element-plus/theme-chalk/dist/table.css'
import '@element-plus/components/src/checkbox/style/css'
import '@element-plus/components/src/tag/style/css'
import '@element-plus/components/src/tooltip/style/css'
import '@element-plus/components/src/scrollbar/style/css'
