export const PKG_PREFIX = '@element-plus'
export const PKG_NAME = 'element-deri'
export const PKG_CAMELCASE_NAME = 'ElementDeri'
export const PKG_CAMELCASE_LOCAL_NAME = 'ElementDeriLocale'
export const PKG_BRAND_NAME = 'Element Deri'
