export const PKG_PREFIX = '@guwave'
export const PKG_NAME = '@guwave/ui'
export const PKG_CAMELCASE_NAME = 'GuboUI'
export const PKG_CAMELCASE_LOCAL_NAME = 'GuboUILocale'
export const PKG_BRAND_NAME = 'Gubo UI'
