name: 'ci'
on:
  push:
    branches:
      - pkg-pr
    tags:
      - '!**'
  pull_request:
    branches:
      - pkg-pr
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Open dist/element-plus
        run: |
          cd dist/element-plus
          ls -la

      - name: Publish
        run: |
          cd dist/element-plus
          pnpx pkg-pr-new publish
