name: Publish PR Commit Pkg

on:
  push:
    branches:
      - dev
    tags:
      - '!**'
  pull_request:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'element-plus/element-plus' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          package-manager-cache: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Get Latest Release Version
        id: get_release
        run: |
          LATEST_VERSION=$(curl -s https://api.github.com/repos/element-plus/element-plus/releases/latest | jq -r '.tag_name')
          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV

      - name: Update package.json version
        run: |
          cd dist/element-plus
          ls -la
          jq --arg newVersion "$LATEST_VERSION" '.version = $newVersion' package.json > tmp.json && mv tmp.json package.json

      - name: Publish for PR
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          cd dist/element-plus
          pnpx pkg-pr-new publish --pnpm --packageManager=pnpm,npm,yarn

      - name: Publish for Commit Push
        if: ${{ github.event_name == 'push' }}
        run: |
          cd dist/element-plus
          pnpx pkg-pr-new publish --pnpm --comment=off --packageManager=pnpm,npm,yarn
