name: 📦 Package Size Report

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  size-report:
    runs-on: ubuntu-latest

    env:
      CI_JOB_NUMBER: 1

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: 'pnpm'

      - uses: preactjs/compressed-size-action@55bc26418aac9d1e7ee232255af3e3e9523ba23b
        id: compressed-size
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: './dist/element-plus/dist/*.{js,mjs,css}'
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Save comment body
        env:
          COMMENT_BODY: ${{ steps.compressed-size.outputs.comment-body }}
        run: printf '%s\n' "$COMMENT_BODY" > ./compressed-size-comment.md

      - name: Save PR number
        env:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
        run: echo "$PULL_REQUEST_NUMBER" > ./compressed-size-pr-number.txt

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: compressed-size-comment
          path: ./compressed-size-comment.md
          retention-days: 1

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: compressed-size-pr-number
          path: ./compressed-size-pr-number.txt
          retention-days: 1
