name: 📦 Package Size Report

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  size-report:
    runs-on: ubuntu-latest

    env:
      CI_JOB_NUMBER: 1

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0e279bb959325dab635dd2c09392533439d90093 # v6.0.8

      - name: Setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: 24
          cache: 'pnpm'

      - uses: preactjs/compressed-size-action@66325aad6443cb7cf89c4bfcd414aea2367cda94 # 2.9.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          pattern: './dist/element-plus/dist/*.{js,mjs,css}'
        env:
          NODE_OPTIONS: --max-old-space-size=4096
