name: 🧪 Unit Test

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build:
    name: Unit Test (${{ matrix.node-name }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.0, 24, 26]
        include:
          - node-version: 22.13.0
            node-name: LTS
          - node-version: 24
            node-name: LTS(24)
          - node-version: 26
            node-name: Current
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Test
        run: pnpm test
